// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx83Y6cWjic42-lSjUeAEIDaNcXjLg3Lc',
    appId: '1:272477724597:web:939ef86df7613a4b31c3fc',
    messagingSenderId: '272477724597',
    projectId: 'styleundermeasure',
    authDomain: 'styleundermeasure.firebaseapp.com',
    storageBucket: 'styleundermeasure.appspot.com',
    measurementId: 'G-WYP4K2N847',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoxdRxijEPMC4JHNbgLZzwyVqVSpqgAwQ',
    appId: '1:272477724597:android:86767eb87a7b486631c3fc',
    messagingSenderId: '272477724597',
    projectId: 'styleundermeasure',
    storageBucket: 'styleundermeasure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCfM_Ne35hi-TBYHSwIsaM9Wev0J_qNmg',
    appId: '1:272477724597:ios:f90c16589ed8ae6231c3fc',
    messagingSenderId: '272477724597',
    projectId: 'styleundermeasure',
    storageBucket: 'styleundermeasure.appspot.com',
    iosClientId: '272477724597-v9qfcfr10lav4trj9o35fevhur10nddo.apps.googleusercontent.com',
    iosBundleId: 'br.com.lighthouse.estiloSobMedida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCfM_Ne35hi-TBYHSwIsaM9Wev0J_qNmg',
    appId: '1:272477724597:ios:f90c16589ed8ae6231c3fc',
    messagingSenderId: '272477724597',
    projectId: 'styleundermeasure',
    storageBucket: 'styleundermeasure.appspot.com',
    iosClientId: '272477724597-v9qfcfr10lav4trj9o35fevhur10nddo.apps.googleusercontent.com',
    iosBundleId: 'br.com.lighthouse.estiloSobMedida',
  );
}
